### ISSUE TITLE
Death coords

### ISSUE THREAD

**Issue by Peas4nt** [jstin9/quick-print-coords#1]
Make it possible for coordinates to be written to everyone when you die. As for me it will be an interesting idea in which it will be possible to realize when playing bingo that players began to hunt for loot.

**Comment by jstin9** [comment]
> Make it possible for coordinates to be written to everyone when you die. As for me it will be an interesting idea in which it will be possible to realize when playing bingo that players began to hunt for loot.

I will think about it
