### ISSUE TITLE
nether coords math.s

### ISSUE THREAD

**Issue by DewandaArya** [jstin9/quick-print-coords#2]
your friend is at 2000 3000 you wanna meet em but thats  far away so use the netehr to get there faster and you cant math  lets add someting like "Nether Coords: x, z," where x and z is just overworld divided by 8 i t a

**Comment by jstin9** [comment]
Thanks a lot for your feedback on the mod, not a bad idea I will implement this soon in the next update.

**Comment by jstin9** [comment]
Done, waiting for your feedback

**Comment by jstin9** [comment]
ok nvm
